datasets:
- json_path: /disk1/dataset/llava_ov_data/real_vision_flan/llava_wild_4v_39k.json # not released
  sampling_strategy: "first:30%"
- json_path: /disk1/dataset/llava_ov_data/real_vision_flan/llava_wild_4v_12k.json # not released
  sampling_strategy: "first:30%"
- json_path: /disk1/dataset/llava_ov_data/real_vision_flan/ai2d_azuregpt_detailed_understanding_4874.json
  sampling_strategy: "first:30%"
- json_path: /disk1/dataset/llava_ov_data/real_vision_flan/infographic_vqa_4404.json
  sampling_strategy: "first:30%"
- json_path: /disk1/dataset/llava_ov_data/real_vision_flan/m4_instruct_annotations.json # released in lmms-lab/M4-Instruct
  sampling_strategy: "first:60000"
- json_path: /disk1/dataset/llava_ov_data/real_vision_flan/0_30_s_academic_oe_v0_1_qa_processed.json # will be released in next version of LLaVA-NeXT-Video
  sampling_strategy: "all"
- json_path: /disk1/dataset/llava_ov_data/real_vision_flan/0_30_s_academic_v0_1_cap_processed.json # will be released in next version of LLaVA-NeXT-Video
  sampling_strategy: "all"